name: CI-TESTS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: jaw123
          POSTGRES_DB: curso
        ports:
          - 8892:5432
        options: >-
          --health-cmd pg_isready -p 8892
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Golang Migrate
        run: |
          sudo curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
          sudo echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
          sudo apt-get update
          sudo apt-get install -y migrate

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Migrate DB
        run: make migrate_up

      - name: Test
        run: make test